const fs=require('node:fs'),path=require('node:path');
const site=path.resolve(__dirname,'..');
const data=JSON.parse(fs.readFileSync(path.join(site,'content','reading.json'),'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
if(!/^\d{4}-\d{2}-\d{2}$/.test(data.lastReviewed))throw Error('Invalid review date');
const seen=new Set();for(const item of data.items){if(seen.has(item.id))throw Error('Duplicate reading id');seen.add(item.id);if(!['news','paper'].includes(item.type))throw Error('Invalid reading type');if(!item.url.startsWith('https://'))throw Error('HTTPS source required');for(const field of ['title','authors','venue','date','dateLabel','summary','relevance'])if(!item[field])throw Error('Missing field '+field);}
const date=new Date(data.lastReviewed+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Singapore'});
function cards(type){return data.items.filter(i=>i.type===type).map(i=>`<article class="reading-card" id="reading-${esc(i.id)}"><p class="reading-meta">${type==='news'?'NEWS &amp; GUIDANCE':'PUBLISHED PAPER'} <span>· ${esc(i.dateLabel)}</span></p><h4><a href="${esc(i.url)}">${esc(i.title)}</a></h4><p class="reading-byline">${esc(i.authors)}<br>${esc(i.venue)}</p><p>${esc(i.summary)}</p><p class="reading-relevance"><strong>Why it matters</strong> ${esc(i.relevance)}</p><a class="text-link" href="${esc(i.url)}">${type==='news'?'Read official update':'Read paper'}</a></article>`).join('\n');}
const section=`  <!-- READING-DESK:START -->
<section id="reading" class="section reading-section" aria-labelledby="reading-title"><div class="wrap"><div class="section-heading horizontal"><div><p class="eyebrow">05 / CURATED READING</p><h2 id="reading-title">On the reading desk.</h2></div><p class="reading-reviewed">Last reviewed<br><time datetime="${data.lastReviewed}">${date}</time></p></div><p class="reading-intro">Selected news and published work by other researchers, with brief context on their relevance to behavioural security, trustworthy AI, and evaluation.</p><div class="reading-group"><h3>Recent developments</h3><div class="reading-news-grid">${cards('news')}</div></div><div class="reading-group"><h3>Research worth revisiting</h3><div class="reading-paper-grid">${cards('paper')}</div></div><p class="reading-footnote">Dates refer to the original source. Summaries and relevance notes are editorial commentary; authorship remains with the credited researchers and organisations.</p></div></section>
  <!-- READING-DESK:END -->`;
const index=path.join(site,'index.html');const html=fs.readFileSync(index,'utf8');const pattern=/  <!-- READING-DESK:START -->[\s\S]*?  <!-- READING-DESK:END -->/;
if(!pattern.test(html))throw Error('Reading markers missing');fs.writeFileSync(index,html.replace(pattern,section));console.log('Built '+data.items.length+' reading entries; reviewed '+data.lastReviewed);
