const fs=require('node:fs'),path=require('node:path');
const site=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(site,'content/papers.json'),'utf8')),reading=JSON.parse(fs.readFileSync(path.join(site,'content/reading.json'),'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const unique=new Map();for(const p of [...data.referencedPapers,...reading.items.filter(p=>p.type==='paper')]){if(!unique.has(p.url))unique.set(p.url,p);}
const other=[...unique.values()];
for(const p of [...data.myPapers,...other]){for(const field of ['title','authors','venue','dateLabel','url'])if(!p[field])throw Error('Missing paper '+field);if(!p.url.startsWith('https://'))throw Error('HTTPS paper source required');}
const cards=items=>items.map(p=>`<article class="paper-link-card"><p class="eyebrow">${esc(p.dateLabel)}</p><h3><a href="${esc(p.url)}">${esc(p.title)}</a></h3><p class="reading-byline">${esc(p.authors)}<br>${esc(p.venue)}</p>${p.note?`<p class="date-note">${esc(p.note)}</p>`:''}<a class="text-link" href="${esc(p.url)}" aria-label="Read paper: ${esc(p.title)}">Read paper at source ↗</a></article>`).join('\n');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Links to Qasim Alriyami's published research and papers cited or featured on his cybersecurity academic website."><meta name="theme-color" content="#08131f"><title>All papers | Qasim Alriyami</title><link rel="canonical" href="https://alriyami7777-alt.github.io/papers.html"><link rel="stylesheet" href="style.css?v=6"></head><body>
<a class="skip" href="#main">Skip to papers</a><header class="header wrap"><a class="brand" href="index.html"><span class="monogram">QA<span>_</span></span><span class="brand-text">QASIM ALRIYAMI<br><small>CYBERSECURITY RESEARCH</small></span></a><nav aria-label="Main navigation"><a href="index.html">Home</a><a href="#my-papers">My publications</a><a href="#other-papers">Other researchers</a><a href="index.html#notes">Notes</a></nav></header>
<main id="main" class="paper-library wrap"><div class="library-intro"><p class="eyebrow">THE PAPER LIBRARY / ${data.myPapers.length+other.length} PAPERS</p><h1>Research, one link away.</h1><p>My published work and the research papers cited or featured across this website, collected in one place.</p><div class="actions"><a class="button primary" href="#my-papers">My publications · ${data.myPapers.length}</a><a class="button" href="#other-papers">Other researchers · ${other.length}</a></div></div>
<section id="my-papers" class="library-group" aria-labelledby="my-papers-title"><h2 id="my-papers-title">My published papers.</h2><p>Journal and conference publications, with links to their original publication records.</p><div class="paper-links-grid">${cards(data.myPapers)}</div></section>
<section id="other-papers" class="library-group" aria-labelledby="other-papers-title"><h2 id="other-papers-title">Papers by other researchers.</h2><p>Published work from the reading desk and research notes. Each entry credits its authors and links to the original source.</p><div class="paper-links-grid">${cards(other)}</div></section>
<p class="library-footnote">Links open the publisher, proceedings or institutional record. Full-text availability depends on the source. News updates and datasets have their own sections on the <a href="index.html#reading">reading desk</a> and in the <a href="index.html#datasets">dataset guide</a>.</p></main><footer class="wrap"><span>© 2026 Qasim Alriyami</span><a href="index.html">Academic website</a><a href="#main">Back to top</a></footer></body></html>\n`;
fs.writeFileSync(path.join(site,'papers.html'),html);console.log('Built paper library: '+data.myPapers.length+' own publications, '+other.length+' external papers.');
